version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - ./database:/app/database
    env_file:
      - .env
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_APP_WEDDING_DATE=${VITE_APP_WEDDING_DATE}
        - VITE_APP_VENUE_LAT=${VITE_APP_VENUE_LAT}
        - VITE_APP_VENUE_LNG=${VITE_APP_VENUE_LNG}
        - VITE_PARTNER1_ACCOUNT_NAME=${VITE_PARTNER1_ACCOUNT_NAME}
        - VITE_PARTNER1_ACCOUNT_NUMBER=${VITE_PARTNER1_ACCOUNT_NUMBER}
        - VITE_PARTNER2_ACCOUNT_NAME=${VITE_PARTNER2_ACCOUNT_NAME}
        - VITE_PARTNER2_ACCOUNT_NUMBER=${VITE_PARTNER2_ACCOUNT_NUMBER}
        - VITE_YOUTUBE_PLAYLIST_URL=${VITE_YOUTUBE_PLAYLIST_URL}
    depends_on:
      - backend
    restart: unless-stopped
    expose:
      - "80"